// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddedtheFlaggedfieldsforPrintswhichwillallowstafftomonitorspecialcasefiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedtheFlaggedfieldsforPrintswhichwillallowstafftomonitorspecialcasefiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201312051938044_Added the Flagged fields for Prints, which will allow staff to monitor special case files."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
