// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class correctedthePrintmodeltostoreMaterialIdsofprintsinastringthatcanbeparsed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctedthePrintmodeltostoreMaterialIdsofprintsinastringthatcanbeparsed));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211736121_corrected the Print model to store MaterialIds of prints in a string that can be parsed."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
