// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class MakingSureallIDsareuptoDateandnoModelchangeshavehappened : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingSureallIDsareuptoDateandnoModelchangeshavehappened));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211601239_Making Sure all IDs are up to Date and no Model changes have happened."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
