// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class prototypedforpauseresumeandregisteringwhatcommandsmachinessupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prototypedforpauseresumeandregisteringwhatcommandsmachinessupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201403191428021_prototyped for pause resume and registering what commands machines support"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
