// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Changednameofaffiliatedmachinetoprinterasitshouldhavebeen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changednameofaffiliatedmachinetoprinterasitshouldhavebeen));
        
        string IMigrationMetadata.Id
        {
            get { return "201402130215039_Changed name of affiliated machine to printer as it should have been"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
