// <auto-generated />
namespace MakerFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddedTaskProgresspropertytoMachinesforpercentileassesmentsofprogress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTaskProgresspropertytoMachinesforpercentileassesmentsofprogress));
        
        string IMigrationMetadata.Id
        {
            get { return "201402040243242_Added Task Progress property to Machines for percentile assesments of progress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
